In [1]:
import numpy as np
import numpy.ma as ma
from ColorDetection import *

# Test code please ignore

In [2]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[0,2,1,255,0],[0,2,1,255,0],[0,2,1,255,0],[0,2,1,255,0]])
mask = b==0
mask

array([[ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True]])

In [3]:
a = np.array([[1,2,3],[1,8,3]])
b = np.array([[0,1,5],[0,1,5]])
np.maximum(a,b)

array([[1, 2, 5],
       [1, 8, 5]])

In [4]:
def rand_color():
    return np.random.randint(256,size=3)

In [5]:
def rand_chunk():
    return np.array([[rand_color(),rand_color()],[rand_color(),rand_color()]])

In [6]:
img = rand_chunk()

In [7]:
def RGB_to_HSVold(rgb):
    
    rows = rgb.shape[0]
    cols = rgb.shape[1]
    hsvImage = np.zeros((rows, cols, 3))
    
    for y in range(rows):
        for x in range(cols):
            redPrime = rgb[y,x,0] / 255
            greenPrime = rgb[y,x,1] / 255
            bluePrime = rgb[y,x,2] / 255
            
            cMax = max(redPrime, greenPrime, bluePrime)
            cMin = min(redPrime, greenPrime, bluePrime)
            delta = cMax - cMin
            
            #hue (color wheel (0 <= hue < 360))
            if delta == 0: #if there is no net hue (no dominating color) of a pixel, set the hue to 0
                hsvImage[y][x][0] = 0
            elif cMax == redPrime:
                hsvImage[y][x][0] = (60 * ((greenPrime - bluePrime) / delta) + 360) % 360 #reds are the first third of the color wheel
            elif cMax == greenPrime:
                hsvImage[y][x][0] = (60 * ((bluePrime - redPrime) / delta) + 120) % 360 #greens are the second third of the color wheel
            elif cMax == bluePrime:
                hsvImage[y][x][0] = (60 * ((redPrime - greenPrime) / delta) + 240) % 360 #blues are the third third of the color wheel
            
            #saturation (lower value is more white, higher value is more colored (0 <= saturation <= 1000))
            if cMax == 0: #black
                hsvImage[y][x][1] = 0
            else:
                hsvImage[y][x][1] = (delta / cMax) * 1000 #in permille
            
            #value (lower value is more black, higher value is more colored (0 <= saturation <= 1000))
            hsvImage[y][x][2] = cMax * 1000 #in permille
    
    return hsvImage

In [8]:
def RGB_to_HSV(rgb):

    # rows = rgb.shape[0]
    # cols = rgb.shape[1]
    hsvImage = np.zeros_like(rgb,dtype='float64')

    redPrime = rgb[:,:,0] / 255
    greenPrime = rgb[:,:,1] / 255
    bluePrime = rgb[:,:,2] / 255

    cMax = np.maximum(np.maximum(redPrime, greenPrime), bluePrime)
    cMin = np.minimum(np.minimum(redPrime, greenPrime), bluePrime)
    delta = cMax - cMin

    #blues are the third third of the color wheel
    blue_max_idx = np.logical_and(cMax == bluePrime, delta != 0)
    hsvImage[blue_max_idx, 0] = (60 * ((redPrime[blue_max_idx] - greenPrime[blue_max_idx]) / delta[blue_max_idx]) + 240) % 360

    #greens are the second third of the color wheel
    green_max_idx = np.logical_and(cMax == greenPrime, delta != 0)
    hsvImage[green_max_idx, 0] = (60 * ((bluePrime[green_max_idx] - redPrime[green_max_idx]) / delta[green_max_idx]) + 120) % 360

    #reds are the first third of the color wheel
    red_max_idx = np.logical_and(cMax == redPrime, delta != 0)
    hsvImage[red_max_idx, 0] = (60 * ((greenPrime[red_max_idx] - bluePrime[red_max_idx]) / delta[red_max_idx]) + 360) % 360

    #if there is no net hue (no dominating color) of a pixel, set the hue to 0
    hsvImage[delta == 0, 0] = 0

    #saturation (lower value is more white, higher value is more colored (0 <= saturation <= 1000))
    hsvImage[cMax != 0, 1] = (delta[cMax != 0] / cMax[cMax != 0]) * 1000

    #value (lower value is more black, higher value is more colored (0 <= saturation <= 1000))
    hsvImage[:,:,2] = cMax * 1000 #in permille

    return hsvImage

In [9]:
for i in range(100):
    img = rand_chunk()
    o = RGB_to_HSVold(img)
    n = RGB_to_HSV(img)
    print(np.any(~np.isclose(o, n)))

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [10]:
RGB_to_HSVold(img)

array([[[144.7826087 , 793.10344828, 454.90196078],
        [ 44.32835821, 680.20304569, 772.54901961]],

       [[305.58139535, 995.37037037, 847.05882353],
        [217.41935484, 953.84615385, 764.70588235]]])

In [11]:
RGB_to_HSV(img)

array([[[144.7826087 , 793.10344828, 454.90196078],
        [ 44.32835821, 680.20304569, 772.54901961]],

       [[305.58139535, 995.37037037, 847.05882353],
        [217.41935484, 953.84615385, 764.70588235]]])

In [12]:
r = img[:,:,0]
g = img[:,:,1]
b = img[:,:,2]
r,g,b

(array([[ 24, 197],
        [216,   9]]),
 array([[116, 162],
        [  1,  79]]),
 array([[ 62,  63],
        [196, 195]]))

In [13]:
np.maximum(np.maximum(r,g),b)

array([[116, 197],
       [216, 195]])

In [14]:
ma = np.maximum(r, g)
ma

array([[116, 197],
       [216,  79]])

In [15]:
r-b

array([[ -38,  134],
       [  20, -186]])

In [16]:
np.logical_and(ma == r,ma == b)

array([[False, False],
       [False, False]])

In [17]:
max(1,2,3)

3

In [18]:
n[ma == r, 0]

array([ 44.32835821, 305.58139535])

In [19]:
n[ma == r, 0] = (r-b)[ma == r]
n[:,:,0]

array([[144.7826087 , 134.        ],
       [ 20.        , 217.41935484]])